export const icons = {
  averageReturn: require('../../assets/icons/average_return.png'),
  browse: require('../../assets/icons/browse.png'),
  close: require('../../assets/icons/close.png'),
  currentValue: require('../../assets/icons/current_value.png'),
  defaultUser: require('../../assets/icons/default_user.png'),
  dropDownArrow: require('../../assets/icons/drop_down_arrow.png'),
  explore: require('../../assets/icons/explore.png'),
  filter: require('../../assets/icons/filter.png'),
  investments: require('../../assets/icons/investments.png'),
  logoName: require('../../assets/icons/logo_name.png'),
  logo: require('../../assets/icons/logo.png'),
  menu: require('../../assets/icons/menu.png'),
  messages: require('../../assets/icons/messages.png'),
  more: require('../../assets/icons/more.png'),
  notification: require('../../assets/icons/notification.png'),
  overview: require('../../assets/icons/overview.png'),
  profile: require('../../assets/icons/profile.png'),
  search: require('../../assets/icons/search.png'),
  settings: require('../../assets/icons/settings.png'),
  taxCenter: require('../../assets/icons/tax_center.png'),
  totalInvested: require('../../assets/icons/total_invested.png'),
  transactions: require('../../assets/icons/transactions.png'),
  downChange: require('../../assets/icons/down_change.png'),
  upChange: require('../../assets/icons/up_change.png'),
  sampleInvestment: require('../../assets/icons/sample_investment.png'),
};
